### ISSUE TITLE
How to select a dl tag with all child in c#

### ISSUE THREAD

**Issue by mohammad983** [zzzprojects/html-agility-pack#230] opened 2018-08-09 16:39 UTC
I have a problem to select all `dt` and `dd` from the blow HTML table

    <dl class="Grid Grid--multicol Grid--2col:40em Grid--4col:60em">
        <div class="Grid-cell u-flex u-flexOne u-flexRow">
            <dt> Item ID:</dt>
            <dd class="u-weightSemibold u-paddingL5px">72547664</dd>
        </div>
        <div class="Grid-cell u-flex u-flexOne u-flexRow">
                <dt> License:</dt>
    			<dd class="u-weightSemibold u-paddingL5px">
    				<a class="u-linkDodgerBlue js-infoLicenseString" href="" target="_blank">Standard</a>
    			</dd>
        </div>
        <div class="Grid-cell u-flex u-flexOne u-flexRow">
                <dt> Usage:</dt>
                <dd class="u-weightSemibold">Commercial<span class="TooltipQuestionMark"></span></dd>
        </div>
        <div class="Grid-cell u-flex u-flexOne u-flexRow">
                <dt> Required Plugins:</dt>
                <dd class="u-weightSemibold u-paddingL5px">None</dd>
        </div>
        <div class="Grid-cell u-flex u-flexOne u-flexRow">
                <dt> Creation Tool:</dt>
                <dd class="u-weightSemibold u-paddingL5px">Autodesk</dd>
        </div>
        <div class="Grid-cell u-flex u-flexOne u-isHidden:0-60em"></div>
    </dl>

I write this
```csharp
                i = 0; doc.DocumentNode.SelectNodes("//dl").Where(x => x.HasClass("Grid")).FirstOrDefault().SelectNodes(".//div").ToList().ForEach(x =>
                {
                    result.Items.Add(new DownloadItem { Name = "specs-title", Index = i,    Type = DownloadItemType.Text, Value = x.SelectNodes(".//dt").FirstOrDefault().GetText() });
                    result.Items.Add(new DownloadItem { Name = "specs",       Index = i++,  Type = DownloadItemType.Text, Value = x.SelectNodes(".//dd").GetText() });
                });
```

The above code just grab the first row
`Item ID:` | `72547664`
whats my problem to list all `dt` and `dd` information

**Comment by JonathanMagnan** [comment] 2018-08-09 19:41
Hello @mohammad983 ,

Do you think you could provide a "working" project example/test with this issue?

It will help my developer investigate the issue more efficiently.

_You can send it to: info@zzzprojects.com if you need to keep the source private_

_We now always ask for a sample project since most issues are either missing some essential information, have some syntax errors or are resolved by the requestor when creating it_

_Having a test project allows us to give faster support and a better experience to users of our free libraries._

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment] 2018-08-09 19:43
Basically, if you want to test it on your side.

Best Regards,

Jonathan
The problem is probably here `x.SelectNodes(".//dt")`

It selects the first `dt` from the root document.

So perhaps modifying it for `x.SelectNodes("//dt")` or `x.SelectNodes("/dt")` will make it works

**Comment by mohammad983** [comment] 2018-08-09 20:36
I have tried it but it does not work!
I sent you an email.
Regards

**Comment by JonathanMagnan** [comment] 2018-08-10 13:44
Hello @mohammad983 ,

The problem in your code is the last `div` doesn't have a `dd` or `dt`

Here is a working version with your code

```csharp
var html = @"
<dl class=""Grid Grid--multicol Grid--2col:40em Grid--4col:60em"">
    <div class=""Grid-cell u-flex u-flexOne u-flexRow"">
        <dt> Item ID:</dt>
        <dd class=""u-weightSemibold u-paddingL5px"">72547664</dd>
    </div>
    <div class=""Grid-cell u-flex u-flexOne u-flexRow"">
            <dt> License:</dt>
			<dd class=""u-weightSemibold u-paddingL5px"">
				<a class=""u-linkDodgerBlue js-infoLicenseString"" href="""" target=""_blank"">Standard</a>
			</dd>
    </div>
    <div class=""Grid-cell u-flex u-flexOne u-flexRow"">
            <dt> Usage:</dt>
            <dd class=""u-weightSemibold"">Commercial<span class=""TooltipQuestionMark""></span></dd>
    </div>
    <div class=""Grid-cell u-flex u-flexOne u-flexRow"">
            <dt> Required Plugins:</dt>
            <dd class=""u-weightSemibold u-paddingL5px"">None</dd>
    </div>
    <div class=""Grid-cell u-flex u-flexOne u-flexRow"">
            <dt> Creation Tool:</dt>
            <dd class=""u-weightSemibold u-paddingL5px"">Autodesk</dd>
    </div>
    <div class=""Grid-cell u-flex u-flexOne u-isHidden:0-60em""></div>
</dl>
";

var doc = new HtmlAgilityPack.HtmlDocument();
doc.LoadHtml(html);
var result = new List<object>();

var i = 0;

doc.DocumentNode.SelectNodes("//dl").Where(x => x.HasClass("Grid")).FirstOrDefault().SelectNodes(".//div").ToList().ForEach(x =>
{
    if (x.SelectSingleNode(".//dt") != null)
    {
        result.Add(new { Name = "specs-title", Index = i, Value = x.SelectSingleNode(".//dt").InnerText });
        result.Add(new { Name = "specs", Index = i++, Value = x.SelectSingleNode(".//dd").InnerText });
    }

});
```

Let me know if that work on your side.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2018-08-19 23:40
Hello @mohammad983 ,

This issue will be closed since it has been answered.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2018-08-19 23:40 UTC
