### ISSUE TITLE
.net45 uri colon issue

### ISSUE THREAD

**Issue by drobok** [zzzprojects/html-agility-pack#38] opened 2017-07-10 19:14 UTC
Is there any chance to bypass of unwanted decoding of colon character (:) by uri class used in your library ("feature" in uri added in .net45) ?. One of servers auto redirecting to %3a and i am unable to use your library to load it. 
I already tried to add configuration options of uri class in my project but it doesnt work. Maybe is there chance to use uri.OriginalString method as url ? I didnt found any public class with string dont parsed later by uri.

**Comment by JonathanMagnan** [comment] 2017-07-10 19:48
Hello @drobok ,

Could you explain better this situation, perhaps an example?

That will help us to reproduce quicker the issue.

Best Regards,

Jonathan

**Comment by drobok** [comment] 2017-07-11 07:19
I will try explain it with example, some string with encoded colon (%3A below), are send by your library
```
string adress = "http://www.filmweb.pl/film/Piraci+z+Karaib%C3%B3w%3A+Zemsta+Salazara-2017-606542";
-HtmlWeb web = new HtmlWeb();
-HtmlAgilityPack.HtmlDocument document = web.Load(adress);
```
That code will produce a request (by wireshark with "tcp.port eq 80")
```
Hypertext Transfer Protocol
    GET /film/Piraci+z+Karaib%C3%B3w:+Zemsta+Salazara-2017-606542 HTTP/1.1\r\n
    User-Agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:x.x.x) Gecko/20041107 Firefox/x.x\r\n
    Host: www.filmweb.pl\r\n
    Connection: Keep-Alive\r\n
    \r\n
    [Full request URI: http://www.filmweb.pl/film/Piraci+z+Karaib%C3%B3w:+Zemsta+Salazara-2017-606542]
    [HTTP request 1/51]
    [Response in frame: 166]
    [Next request in frame: 167]
```
Now u see what i mean ? That colon is parsed by uri class (default, by constructor, added to .net45 or later). And now i have a problem, cause webside doesnt support new colon representation standard forced by .net45+. And i have 301 to link with %3A, uri are used while redirect and i have few iterations loop.

Now i have add option to constructor of uri class
https://stackoverflow.com/questions/2515959/how-to-create-a-uri-instance-parsed-with-genericuriparseroptions-dontcompresspat 
but it doesnt work when i use dll
Or use uri_class_variable.OriginalString when sending request

That fixed require (probably) from me modify of your code or i am blind and didn't saw the swith for that.

**Comment by JonathanMagnan** [comment] 2017-07-11 12:04
Hello @drobok ,

Thank you, you give us enough information to investigate this issue.

We can easily reproduce the same issue as you.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-07-16 22:15
Hello @drobok ,

Since the Uri class is not a class we control, I believe the best is probably fixing a workaround from the config file.

Could you try by adding this to your config file?

```txt
<uri>
<schemeSettings>
    <add name="http" genericUriParserOptions="DontUnescapePathDotsAndSlashes" />
</schemeSettings>
</uri>
```

Source: https://connect.microsoft.com/VisualStudio/feedback/details/511010/erroneous-uri-parsing-for-encoded-reserved-characters-according-to-rfc-3986

Let me know if that successfully solve your issue.

Best Regards,

Jonathan

**Comment by drobok** [comment] 2017-07-17 15:06
I already tried that before posting here, it doesnt work ;(

**Comment by JonathanMagnan** [comment] 2017-07-17 18:03
Hello @drobok ,

You are right, I'm not sure why I got a result yesterday.

I tried again today, and it always returns me an empty document. We will look if we can find something else, in worse case scenario (or perhaps the better case), we will add a new overload that takes an Uri.

By forcing the Uri to don't use escaping, it works.

```csharp
Uri uri = new Uri(url, true);
```

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-07-22 15:37
Hello @drobok ,

The v1.5.2-beta3 has been released.

Since we didn't find a way to fix it yet and adding an overload method that takes a Uri instead of a string URL make sense, we added this overload.

Here is an example of use:

```csharp
string adress = "http://www.filmweb.pl/film/Piraci+z+Karaib%C3%B3w%3A+Zemsta+Salazara-2017-606542";
var uri = new Uri(adress, true);
HtmlWeb web = new HtmlWeb();
HtmlAgilityPack.HtmlDocument document = web.Load(uri);
```

Let me know if that succesfully fix your issue.

Best Regards,

Jonathan

**Comment by damian12345** [comment] 2017-07-24 13:25
Unfortunately, it not works:
web.Load(uri); <- invalid argument (uri isn't a string)
uri.ToString() / uri.AbsoulteUri / uri.AbsoultePath etc. etc. still not works :(

**Comment by JonathanMagnan** [comment] 2017-07-24 19:16
Hello @damian12345 ,

Have you updated correctly to the v1.5.2-beta3?

The overload that supports URI has been added to this version. I just tried it on my dev environment directly from the NuGet package and it works fine.

Best Regards,

Jonathan

**Comment by drobok** [comment] 2017-07-25 07:54
Overload in library works, but still i have issue with colon character. Your solution (2nd parameter in constructor set to true is deprecated in .net4.5 and is set always false.

I think DontUnescapePathDotsAndSlashes doesnt work for colon character ;( Maybe some overload with uri.AbsoluteUri ?

**Comment by damian12345** [comment] 2017-07-25 11:14
My fault, I didn't update it.
But after update still not works

**Comment by JonathanMagnan** [comment] 2017-07-25 12:55
I'm aware this method is obsolete since the version .NET 4.5 but on my side this is still working... from 4.5 to the latest version.

> 2nd parameter in constructor set to true is deprecated in .net4.5 and is set always false.

Probably mean the method still works but by default, this parameter is always false when not using the overload with the `dontEscape` parameter.

We will continue to investigate this issue and find out why that's working fine on our side and not on both your.

**Comment by JonathanMagnan** [comment] 2017-07-28 21:04
Unfortunately, I believe we will have to pause it for a few days/weeks on our side.

So unless you find out or someone a way to make it work using the code below, we will pause the support on this request:

```csharp
string adress = "http://www.filmweb.pl/film/Piraci+z+Karaib%C3%B3w%3A+Zemsta+Salazara-2017-606542";

var uri = new Uri(adress);
// ???
var req = WebRequest.Create(uri) as HttpWebRequest;
var resp = req.GetResponse() as HttpWebResponse;
```

**Comment by JonathanMagnan** [comment] 2017-08-07 14:14
Hello @drobok , @damian12345 ,

Since I believe this issue is outside of our library, I will close it.

Feel free to re-open it or comment if you can add some information that can be useful to create a fix.

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2017-08-07 14:14 UTC
