### ISSUE TITLE
Cloning/Copying a node does not preserve quotes

### ISSUE THREAD

**Issue by mikalai-sauchanka** [zzzprojects/html-agility-pack#11] opened 2017-06-01 12:27 UTC
`<div attr='test'></div>`

after cloning becomes

`<div attr="test"></div>`

**Comment by JonathanMagnan** [comment] 2017-06-01 12:49
Hello @mikalai-sauchanka ,

Thank you, we successfully reproduce this issue.

```csharp
var html = @"<div attr='test'></div>";

var htmlDoc = new HtmlAgilityPack.HtmlDocument();
htmlDoc.LoadHtml(html);

var divNode = htmlDoc.DocumentNode.SelectSingleNode("//div");

HtmlNode newNode = HtmlNode.CreateNode("<body></body>");
newNode.CopyFrom(divNode);
```

The issue is caused because the QuoteType are not passed to the CreateAttribute method.

We will try to look it more deeply this weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-06-06 00:22
Hello @mikalai-sauchanka ,

Both methods has been fixed, we hope to release the fix on Tuesday.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-06-07 01:44
Hello @mikalai-sauchanka ,

The v1.5.0-beta6 has been released.

The QuoteType is now copied for CloneNode and CopyFrom.

Let me know if that's working.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-06-17 14:44
Closing comment: No answer, feel free to re-open if you still have the issue

**Closed by JonathanMagnan** 2017-06-17 14:44 UTC
