### ISSUE TITLE
NET Standard 2 Incompatibility

### ISSUE THREAD

**Issue by ColinM9991** [zzzprojects/html-agility-pack#81] opened 2017-09-25 18:57 UTC
I've been working on a new NET Standard 2.0 project which uses HtmlAgilityPack to parse and read HTML content. When I attempt to consume my NET Standard library from a NET Framework application, and the code gets so far as to execute the HtmlAgilityPack code then I am presented with the following exception.

`System.IO.FileNotFoundException: 'Could not load file or assembly 'HtmlAgilityPack, Version=1.5.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.'`

I have created a simple solution which demonstrates this issue [Here](https://github.com/ColinM9991/HtmlAgilityPackBug)

**Comment by ColinM9991** [comment] 2017-09-25 19:21
Closing this as this is actually the wrong issue to report.

**Comment by twsouthwick** [comment] 2017-10-06 16:44
I've filed a root cause issue of this: #86

**Comment by ColinM9991** [comment] 2017-10-06 17:07
Reopening as this has gotten exposure.

@twsouthwicm
I've found that the following element in the    csproj file does the trick
`<DependsOnNETStandard>True</DependsOnNETStandard>`

**Comment by JonathanMagnan** [comment] 2017-10-08 13:36
Hello @twsouthwick , and @ColinM9991 ,

I will close this issue since I don't think either that was related to Html Agility Pack.

Thank you for the link @ColinM9991 

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2017-10-08 13:36 UTC

**Comment by twsouthwick** [comment] 2017-10-08 16:55
Please see the issue in #86 that describes why this is happening. The issues you linked to may be similar, but have to do more with resolving the correct version of an assembly. Please note that the entire, full assembly name including strong name, of what it is trying to resolve are consistent except for version. Version can be redirected with binding redirects, but assembly name and strong key cannot be.

The workaround you post will work when creating a .NET Standard 2.0 library and referencing from .NET 4.7. However, if you only have a portable version of some library, which depends on HtmlAgilityPack, and try to include it in a .NET Framework application, you will encounter the same error. This is because .NET Standard and the portable versions of HtmlAgilityPack are not signed.

**Comment by JonathanMagnan** [comment] 2017-10-08 17:42
Thank you @twsouthwick ,

Strong naming versions inconsistently has been fixed and will be released later today or tomorrow, so we will follow this problem in the issue you opened instead #86
