### ISSUE TITLE
Parsing finds only first "select" in a div

### ISSUE THREAD

**Issue by dmspicer** [zzzprojects/html-agility-pack#6] opened 2017-05-24 15:18 UTC
I'm attempting to parse a web page that has three selects embedded in a single div. There is one select in a separate div just above this div. My attempts to parse this return only the first select in each div. 

My most recent attempt is:
[var htmlNodes = document.DocumentNode.SelectNodes("//select");](url)
This returns two HtmlNodes, one for the Id edit-species-type and the other for the Id edit-tid. Nothing for Id edit-tid-select-1 or edit-tid-select-2.

I am including a screen shot of the div in question.
![image](https://cloud.githubusercontent.com/assets/11218900/26410437/4b557a04-4071-11e7-905b-533d54b5dc0a.png)

Any suggestions as to how to get the these?

Thanks,
Dave

**Comment by JonathanMagnan** [comment] 2017-05-24 16:05
Hello @dmspicer ,

Your recent attempts should not return all select and not only two HtmlNodes? Perhaps there is something I didn't understand correctly in your request.

I believe the following XPath will return the first select of every parent

```csharp
// Yes, the index must be 1 and not 0
var htmlNodes = htmlDoc.DocumentNode.SelectNodes("//select[1]");
```

Let me know if that's working.

Best Regards,

Jonathan

**Comment by dmspicer** [comment] 2017-05-24 16:56
I need to return the second and third select in the second div. Ids edit-tid-select-1 and edit-tid-select-2.

[var htmlNodes = document.DocumentNode.SelectNodes("//select[2]");](url) 
returns nothing as does and index of three.

Thanks,
Dave

**Comment by JonathanMagnan** [comment] 2017-05-24 19:21
Hello @dmspicer ,

Here is a code example that handles or show how to handle most cases with your scenario.

```csharp
var html = @"
<div>
    <select name='select_1'></select>
</div>
<div>
    <select name='select_2'></select>
    <select id='select_3'></select>
    <select id='select_4'></select></div>
<div>
";

var htmlDoc = new HtmlAgilityPack.HtmlDocument();
htmlDoc.LoadHtml(html);

// return select_1, select_2, select_3, select4
var htmlNodes1 = htmlDoc.DocumentNode.SelectNodes("//select");

// return select_1, select_2
var htmlNodes2 = htmlDoc.DocumentNode.SelectNodes("//select[1]");

// return select_3, select_4
var htmlNodes3 = htmlDoc.DocumentNode.SelectNodes("//select[position()>1]");
```

I currently start to believe the issue could be more in the HTML you parse since everything look to work in my examples easily.

If that's the case, could you replace the issue in the same way as the example I provided and provide me the expected result?

Best Regards,

Jonathan

**Comment by dmspicer** [comment] 2017-05-24 22:43
I copied your code in to mine and it does what you expected. 

I then copied the central part of the web page I am attempting to parse into my code replacing var html = with it. That works as you would expect it to so I'm guessing there must be something else in the web page that is affecting this. 

Here is what I copied from the web page.
[var html = @"
                <div class='pane - content'>
                    < form id = 'views-exposed-form-checklists-panel-pane-1' action = '/checklists' method = 'get' accept - charset = 'UTF-8' >
                        <div>
                            <div class='views-exposed-form'>
                                <div class='views - exposed - widgets clearfix'>
                                    < div class='views - exposed - widget views - widget - filter - field_species_type_value' id='edit - species - type - wrapper'>
                                        < label for= 'edit-species-type' >
                                                 Species Type </ label >              
                                        < div class='views-widget'>
                                            <div class='form-item form-item-species-type form-type-select form-group'>
                                                <select name = 'species_type' class='form-control form-select' id='edit-species-type'>
                                                    <option value = 'All' > -Any -</ option >
                                                    < option selected='selected' value='0'>butterfly</option>
                                                    <option value = '1' > moth </ option >
                                                </ select >
                                            </ div >
                                        </ div >
                                    </ div >
       
                                    <div class='views - widget'>
                                        < div class='form-item form-item-tid form-type-select form-group shs-wrapper-processed'>
                                            <select name = 'tid' class='element-invisible shs-enabled form-control form-select shs-processed' id='edit-tid' style='display: none;'>
                                                <option value = 'All > -Any -</ option >
                                                <option value='47454'>Abbeville County</option>
                                                <option value = '46478' > Acadia Parish</option><
                                                ><option class='has - children' value='45220'>Wyoming</option>
                                            </select>
                                            <select class='shs - select form - select shs - select - level - 1' id='edit - tid - select - 1' style='display: inline - block; '>
                                                <option value='All'>- Any -</option>' 
                                                <option value='45172'>Barbados</option>
                                                <option class='has - children' value='45159'>Belize</option>
                                                <option class='has - children' value='45152'>United States</option>
                                            </select>
                                            <select class='shs - select form - select shs - select - level - 2' id='edit - tid - select - 2' style='display: inline - block; '>
                                                <option value='All'>- Any -</option>
                                                <option class='has - children' value='45175'>Alabama</option>
                                                <option class='has - children' value='45176'>Alaska</option>
                                                <option class='has - children' value='45177'>Arizona</option>
                                                <option class='has - children' value='45178'>Arkansas</option>
                                            </select>
                                        </div>
                                    </div>
                                 </ div >
                            </ div >
                        </ div >
                    </form>
                </ div >
                ";](url)

The URL for the page I am attempting to parse is
https://www.butterfliesandmoths.org/checklists?species_type=0&tid=45152&items_per_page=All

If there is anything else you can suggest I would appreciate it.

Thanks,
Dave

**Comment by JonathanMagnan** [comment] 2017-05-24 22:58
Hello @dmspicer ,

Looking at the source code, only 2 `select` exists which are correctly parsed by the library. I believe the two additional select are generated from JavaScript.

That will explain why the library can only find two.

Currently, there is no built-in mechanism in HtmlAgilityPack, so you will need to load it in a WebBrowser and get the content.

You can find some similar answer here: [Running Scripts in Html Agility Pack](https://stackoverflow.com/a/11394830/5619143)

I will investigate during the weekend if we should add an option to automatically doing it this kind of behavior.

Best Regards,

Jonathan

**Comment by dmspicer** [comment] 2017-06-01 15:47
Jonathan,

Thanks for the info. I still haven't found another way to do this so if you have a chance to look into the possibility of handling this type of situation from within HtmlAgilityPack I would appreciate it.

Thanks,
Dave

**Comment by JonathanMagnan** [comment] 2017-06-01 15:50
Hello dmspicer,

The solution is almost completed. Currently, only some naming and options need to be confirmed.

I hope to release a new method named `LoadFromBrowser` on this weekend.

It will get more time to load (All script and everything else needs to be loaded...) but it will give the good HTML at least.

Best Regards,

Jonathan

**Comment by dmspicer** [comment] 2017-06-01 15:56
Sounds good! Let me know when it's ready to test. And whatever I need to know to use it.

Thanks,
Dave

**Comment by dmspicer** [comment] 2017-06-19 12:20
Jonathan,

Any progress on the LoadFromBrowser method?

Thanks,
Dave

**Comment by JonathanMagnan** [comment] 2017-06-19 12:50
Hello @dmspicer ,

Sorry for the delay. We have implemented it but never released it yet.

We currently try to find a working alternative for Application.DoEvents which is currently used. If we don't successfully implement an alternative this week, we will release a first version of the method with Application.DoEvents.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-06-24 18:28
Hello @dmspicer ,

The latest version contains a new method named LoadFromBrowser. Be careful, since a WebBrowser is used, they have some memory leak. After a lot of research, we have not found any solution that fixes the memory leak from the web browser control.

Here is an example of use

```csharp
// Example 1
var web = new HtmlWeb();
var doc = web.LoadFromBrowser(url, (WebBrowser browser) => true);
var html = doc.DocumentNode.OuterHtml;

// Example 2
var web = new HtmlWeb();
var doc = web.LoadFromBrowser(url, html =>
{
    return !html.Contains("Loading...");
});
var html = doc.DocumentNode.OuterHtml;
```

We will very soon release a new documentation page that will better explain the functionalities && limitations of this new method

Best Regards,

Jonathan

**Comment by dmspicer** [comment] 2017-06-24 21:25
@JonathanMagnan,

Thanks. I've implemented this in my console application using example 1. 

I ran it once to see what type of variables doc and html were. 

Since the variable doc was a HtmlAgilityPack.HtmlDocument which is what my parsing code uses I ran it again to see what selects were found. I'm still not getting the selects that are created with JavaScript. 

I then attempted to run it again to see what was in the html variable. Now the code never comes back from the execution of LoadFromBrowser. I've tried restarting Visual Studio, even shutting down my system and rebooting it but still hangs. The last time I attempted to run I left it running for over 5 minutes with no response. 

The URL I'm hitting is:
http://www.butterfliesandmoths.org/checklists?species_type=0&tid=45175&items_per_page=All

Any suggestions?

Thanks,
Dave

**Comment by dmspicer** [comment] 2017-06-25 15:10
@JonathanMagnan,

I did some more testing this morning. I changed my code to use example 2. I was able to do one execution. After that the code hangs at LoadFromBrowser like before.

I examined the resulting data in the variable html and it does not have the additional selects that appear to be being generated via JavaScript.

I'm not sure where this leaves us. Am I missing something?

Thanks,
Dave

**Comment by JonathanMagnan** [comment] 2017-06-27 02:15
Hello @dmspicer ,

We made additional test. 

We have run the page directly in the WebBrowser control and it seems the script that create the additional `SELECT` fail for an unknown reason.

So obviously, that will not work either in HAP since we use a web browser under the hood.

Unfortunately, I don't think this page will work ;(

The only option left if opening a real web browser or using an alternative web browser control library than the one provided by Microsoft.

**Comment by JonathanMagnan** [comment] 2017-09-23 19:29
Hello @dmspicer ,

I will close this issue since I don't believe we can do anything on it as we get the same behavior than the `WebBrowser`. 

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2017-09-23 19:29 UTC
