### ISSUE TITLE
cannot scrap text or password fields only from this html site https://account.genndi.com/login

### ISSUE THREAD

**Issue by MKKSPeiris** [zzzprojects/html-agility-pack#196] opened 2018-05-11 06:45 UTC
this is xpath that is used to scrap "//input[@type='text'] | //input[@type='password']" ,but only for [https://account.genndi.com/login](url) website it is not working.

**Comment by JonathanMagnan** [comment] 2018-05-13 13:52
Hello @MKKSPeiris ,

Do you think you could provide us a project example/test with this issue?

It will make easier/faster for my developer to getting started for investigating it.

_We now always ask for a project since we found out that most issues are missing some essential information or are resolved by the requestor when creating it_

_(Even if the issue seem very easy to reproduce, by getting a test project, it allow us to give a faster support and better experience for the support of all our free libraries)_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by MKKSPeiris** [comment] 2018-05-15 09:40
This is my code that i wrote to scrap input field names from html.This code working fine for all other site that i checked except [https://account.genndi.com/login](url) . Code : `inputs_raw = (doc.DocumentNode.SelectNodes("//input[@type='text'] | //input[@type='password']")).Where(node => !string.IsNullOrEmpty(node.Attributes["name"].Value)).Select(value => value.Attributes["name"].Value).ToList();`

**Comment by JonathanMagnan** [comment] 2018-05-15 12:26
Hello @MKKSPeiris ,

The issue is caused because you try to get the attribute name for every input with type = 'text'

However, they don't have all a name such as:

```html
<input type="text" class="form-control" placeholder="Enter your email here..." id="resetPasswordEmail">
```

This input throws the error.

You can easily fix it by checking if the name attribute exists first before trying to get the value

```csharp
var inputs_raw = (doc.DocumentNode.SelectNodes("//input[@type='text'] | //input[@type='password']"))
			        .Where(node => node.Attributes["name"] != null && !string.IsNullOrEmpty(node.Attributes["name"].Value))
			        .Select(value => value.Attributes["name"].Value).ToList();
```

Let me know if that solves your issue.

Best Regards,

Jonathan

**Comment by MKKSPeiris** [comment] 2018-05-17 03:50
yes but in my case there is a tribute called "name" for both inputs.But scraper cant identify that.
`<input type="text" **name="username"** class="required form-control" value="" placeholder="Enter your username...">`
`<input **name="password"** type="password" class="required form-control" style="" placeholder="Enter your password...">`

**Comment by JonathanMagnan** [comment] 2018-05-17 10:51
I don't understand your last comment,

What doesn't work in the provided solution?

**Comment by MKKSPeiris** [comment] 2018-05-18 09:28
`var inputs_raw = (doc.DocumentNode.SelectNodes("//input[@type='text'] | //input[@type='password']"))
			        .Where(node => node.Attributes["name"] != null && !string.IsNullOrEmpty(node.Attributes["name"].Value))
			        .Select(value => value.Attributes["name"].Value).ToList();`
 this code that you send me before also having same problem.It cant scrap from [https://account.genndi.com/login](url) ,**Only from this site**.If you visit that site you will see two inputs to "username" and "password". And those element have name attribute . Why cant i scrap it?.

**Comment by JonathanMagnan** [comment] 2018-05-18 12:33
It works like a charm here

```csharp
string url = "https://account.genndi.com/login";
var doc = new HtmlWeb().Load(url);
var outer = doc.DocumentNode.OuterHtml;

var inputs_raw = (doc.DocumentNode.SelectNodes("//input[@type='text'] | //input[@type='password']"))
	.Where(node => node.Attributes["name"] != null && !string.IsNullOrEmpty(node.Attributes["name"].Value))
	.Select(value => value.Attributes["name"].Value).ToList();
```

Please provide me a full code that doesn't work as I did.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2018-05-22 10:49
Hello @MKKSPeiris ,

Could you provide us a full project with the error? Again, the code you provided is working fine on our side. Maybe a critical line has been removed from your example?

```csharp
string url = "https://account.genndi.com/login";

var htmlweb = new HtmlWeb();
var doc = htmlweb.Load(url);
var inputs_raw = new List<string>();

try
{
	inputs_raw = (doc.DocumentNode.SelectNodes("//input[@type='text'] | //input[@type='password']"))
		.Where(node => node.Attributes["name"] != null && !string.IsNullOrEmpty(node.Attributes["name"].Value))
		.Select(value => value.Attributes["name"].Value).ToList();

	string s = "";
	foreach (string x in inputs_raw)
	{
		s += x;
	}
}
catch (Exception ex)
{
}
```

I'm not sure to understand what that's working for us and not for you.

Best Regards,

Jonathan

**Comment by MKKSPeiris** [comment] 2018-05-24 04:45
I fixed that issue by updating html agility pack.And your solution working fine now Now .Much appreciated your support and time on this problem Jonathan.Thank you very much.

**Comment by JonathanMagnan** [comment] 2018-05-24 11:49
Great :)

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2018-05-24 11:49 UTC
