### ISSUE TITLE
Serialization doesn't support html encoding

### ISSUE THREAD

**Issue by omrycarmel** [zzzprojects/html-agility-pack#316] opened 2019-07-16 16:18 UTC
Description:
Loading a serialized HTML document that has html encoding in it - builts the DOM differently.
This is because the serialized string reflects the decoded HTML.

I've added a code with test function that you can use.
.Net version: 4.7.2, HAP version: latest

Edit:
I removed the fiddle link because fiddle decoded the html decoding string in the code.
I've sent code sample to:
‫info@zzzprojects.com‬

Thanks

**Comment by JonathanMagnan** [comment] 2019-07-16 18:30
Hello @omrycarmel ,

Thank you for the Fiddle (not compiling is not a problem as long as we have the code to reproduce it).

We will look at it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment] 2019-07-19 05:21
Hello @omrycarmel ,

The v1.11.10 has been released.

Could you try it and let me know if this issue is correctly fixed on your side.

**Comment by omrycarmel** [comment] 2019-07-22 07:40
I dont see any change in the behaviour,
The test function that I sent you still fail.
Does it work for you?

**Comment by JonathanMagnan** [comment] 2019-07-22 17:53
Hello @omrycarmel ,

Unfortunately, we had to hide the version with your fix due to a mistake of our part (on another fix). That's why you didn't see your fix when you tried it.

The v1.11.11 has been released, could you try it?

**Comment by omrycarmel** [comment] 2019-07-23 12:06
Thanks for the quick responses,

I just updated to 1.11.11 and the test program that I sent still doesn't work

**Comment by JonathanMagnan** [comment] 2019-07-24 03:09
Hello @omrycarmel ,

What exactly doesn't work? It seems to work fine on our side, see here: https://dotnetfiddle.net/wPvGol

**Comment by JonathanMagnan** [comment] 2019-07-24 03:13
I also tried the one you provided by email, it also return true.

**Comment by omrycarmel** [comment] 2019-07-24 06:43
Sorry, my mistake, it works :)

Thanks!

**Closed** 2019-07-24 06:45 UTC
