### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by udayashree** [zzzprojects/html-agility-pack#98] opened 2017-11-07 02:43 UTC
Hi,

I'm getting the below error often in my program but when I restart my program it works fine again after some time I'm getting null reference exception, though the node is present in the web site it showing me as null as below

System.NullReferenceException: 'Object reference not set to an instance of an object.'

HtmlAgilityPack.HtmlNode.SelectSingleNode(...) returned null.

Below is line throwing error
HtmlNode node = document.DocumentNode.SelectSingleNode("//table[@class='tableBorder trBgBlue tdAlignC font13 fontStyle']");

This works fine but sometimes I'm getting null exception again when I re-run my program it works fine with no exception

**Comment by JonathanMagnan** [comment] 2017-11-07 02:54
Hello @udayashree ,

Unfortunately, this issue is missing too much information to reproduce it or find the error.

I believe the issue is more in your code otherwise with the number of people using this library, it would have been reported way before. But we never know!

If you can easily reproduce it, I recommend you to add this two `null check`.

```csharp
if(document == null)
{
	throw new Exception("Oops! Document is null... must find out why!)
}
else if(document.DocumentNode == null)
{
	throw new Exception("Oops! DocumentNode is null... must find out why!)
}
```

So if one of this error are throw, it could maybe help you to find out where the issue come.

I believe for an unknown reason, your document becomes `null` somewhere in your code.

Let me know if you find out why this is happening.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-11-21 01:45
Hello @udayashree ,

Do you think you could provide us additional information?

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment] 2017-12-13 19:53
Hello @udayashree ,

We are currently making some issue cleanup by closing some unanswered question.

Feel free to reopen if you can provide us additional information.

Best Regards,

Jonathan


---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by yespetruk** [comment] 2018-01-15 08:56
Hello, i have exactly the same problem. An error arises from time to time and I can not understand what's wrong. Here is my code (error is thrown on a first SelectSingleNode, but if i comment it, the error will be on the next SelectSingleNode for example "product.img" ):
` public ActionResult AddProductLink(string link)
        {

            Product product = new Product();
            HtmlWeb web = new HtmlWeb();
            var htmlDoc = web.Load(link);
            product.Price = Convert.ToDouble(htmlDoc.DocumentNode.SelectSingleNode("//span[@id='priceblock_ourprice'] | //span[@id='priceblock_dealprice']").InnerText.Substring(1));
            product.Img = htmlDoc.DocumentNode.SelectSingleNode("//span[@class='a-button-text']/img").Attributes["src"].Value;
            product.Name = htmlDoc.DocumentNode.SelectSingleNode("//span[@id='productTitle']").InnerText.Trim();
            product.Url = link;
            db.Products.Add(product);
            db.SaveChanges();


            string response = JsonConvert.SerializeObject(product);

            return Json(response);
        }`
The link is loaded 100%, it is amazon product page, and specific span with price is present on the page.

**Comment by JonathanMagnan** [comment] 2018-01-15 19:49
Hello @yespetruk ,

Thank you, we will try your scenario on a few Amazon product page to see if we can reproduce it.

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment] 2018-01-19 20:01
Hello @yespetruk ,

We started to investigate this issue but we found out that `Amazon` sometime block your request with the following message in the HTML:

>

I believe your issue might be only this which our library cannot do anything against.

If you believe you can reproduce this issue on a website without being blocked, let us know and we will investigate it more.

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by udayashree** [comment] 2018-01-22 06:36
Hi Jonathan,

Meanwhile, can you help in figuring out whether the below website also blocks the request? 
http://racing.hkjc.com/racing/Info/meeting/Results/english/Local/20171227/HV/1

Below is my code
string url ="http://racing.hkjc.com/racing/Info/meeting/Results/english/Local/20171227/HV/1"
 var htmlDoc = new HtmlDocument();
            htmlDoc.OptionReadEncoding = false;
            var request = (HttpWebRequest)WebRequest.Create(url);
            request.Method = "GET";
            using (var response = (HttpWebResponse)request.GetResponse())
            {
                using (var stream = response.GetResponseStream())
                {
                    htmlDoc.Load(stream, Encoding.UTF8);
                }
            }

            HtmlNode tableNode = htmlDoc.DocumentNode.SelectSingleNode("//table[contains(@class,'tdAlignC')])[2]");

The website is loading correctly, but sometimes Im getting null value in this line
 HtmlNode tableNode = htmlDoc.DocumentNode.SelectSingleNode("(//table[contains(@class,'tdAlignC')])[2]");

**Comment by JonathanMagnan** [comment] 2018-01-22 12:51
Hello @udayashree ,

I don't think that's related to our library. If you are getting sometimes null value, make sure to log the `HTML` somewhere and be able to check yourself whether the current URL is blocked or not.

Unfortunately, we cannot check if every request is blocked or not ;(

Best Regards,

Jonathan

**Comment by udayashree** [comment] 2018-01-23 03:34
Hi Jonathan,

I have attached the screenshot of the table node alone showing null for your reference.
![node](https://user-images.githubusercontent.com/28596694/35256907-3efe8284-0031-11e8-8c74-2b1219bd8e86.PNG)

I'm getting a depth level exception message.

**Comment by JonathanMagnan** [comment] 2018-01-28 15:09
Hello @udayashree ,

Thank you for this additional information,

We will look about this exception.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2018-02-02 16:35
Hello @udayashree ,

We made some test and everything is fine every time.

We even made some loop using your code

```csharp
HtmlNode tableNode = htmlDoc.DocumentNode.SelectSingleNode("(//table[contains(@class,'tdAlignC')])[2]");

if (tableNode == null)
{
    throw new Exception("Oops! table is null");
}
```

but unfortunately we are not able to reproduce it ;(

Are you getting an error on this page (http://racing.hkjc.com/racing/Info/meeting/Results/english/Local/20171227/HV/1)? Or that's on some page that you try to get value from?

Best Regards,

Jonathan

**Closed** 2018-02-13 00:26 UTC
