### ISSUE TITLE
StackOverflowException on HtmlDocument Save

### ISSUE THREAD

**Issue by Janek91** [zzzprojects/html-agility-pack#116] opened 2017-12-10 14:08 UTC
If HtmlDocument has changed and Text of any HtmlNode is null - Save method throws StackOverflowException. Getting Text property of node leads to getting OuterHtml, because Text is null. Because document was changed, getting OuterHtml calls UpdateHtml method which tries to get OuterHtml using WriteTo method. This one tries to get Text property of node and our circle is closed.
Please fix this bug.

**Comment by JonathanMagnan** [comment] 2017-12-10 19:04
Hello @Janek91 ,

Thank you for reporting, we will look at it this week.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment] 2017-12-16 16:57
Hello @Janek91 ,

My developer tried your scenario but couldn't easily reproduce it.

Do you think you could help him and providing an example that reproduces the issue from scratch a little bit similar to this:

```csharp
var html = @"
<body>
<div></div>
<div>with text</div>
</body>
";
var doc = new HtmlAgilityPack.HtmlDocument();
doc.LoadHtml(html);
                
// Make modification
var firstDiv = doc.DocumentNode.SelectSingleNode("//div");
firstDiv.Id = "the_id";

doc.Save(@"C:\Users\Jonathan\Desktop\GeneratedFiles\TestSave.txt");
```

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment] 2018-01-09 20:56
Hello @Janek91 ,

I will close this issue since we cannot go further in our investigation.

Feel free to reopen it if you can provide us more information.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Closed by JonathanMagnan** 2018-01-09 20:56 UTC
