### ISSUE TITLE
">" inside "a" element "href" attribute causes value truncation

### ISSUE THREAD

**Issue by mikehenry1979-bah** [zzzprojects/html-agility-pack#570] opened 2024-09-26 12:45 UTC
I am using this very cool package v1.11.66 to add attributes to "a" elements in PHP source code files. I am only running across one snag that does not cause an exception. If I parse an element such as:
<a target=\"_blank\" href=\"$CFG->wwwroot/course/view.php?id=$course->id\">$shortname</a> ->

Instead of getting $CFG->wwwroot/course/view.php?id=$course->id for the "href" attribute value, I only get $CFG-

Note that those are literal \ and not escape characters. I can work around this by changing the HTML to <a target=\"_blank\" href=\"$CFG-&gt;wwwroot/course/view.php?id=$course-&gt;id\">$shortname</a> -> before parsing it, but it would be nice if this could be handled since it's contained inside the " pair. I'm guessing it's also a possibility that the \" containment vs " is causing the problem.

**Comment by mikehenry1979-bah** [comment] 2024-09-26 12:50
Ah, markdown interfered with my post. Please see attachment.
[HAP sample.txt](https://github.com/user-attachments/files/17148700/HAP.sample.txt)

**Comment by mikehenry1979-bah** [comment] 2024-09-26 13:14
Also, this line parses properly: $string['click_to_continue'] = '<a href="{$a->link}" target="_top" rel="noopener noreferrer">Click to continue</a>';

**Comment by mikehenry1979-bah** [comment] 2024-09-26 13:14
Also, the attached line does parse properly.
[HAP sample 2.txt](https://github.com/user-attachments/files/17149012/HAP.sample.2.txt)

**Comment by JonathanMagnan** [comment] 2024-09-26 14:35
Hello @mikehenry1979-bah ,

Thank you for reporting.

We will look at it very soon.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment] 2024-09-27 16:40
Hello @mikehenry1979-bah ,

Do you think you could create a Fiddle or a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue.

I just made a simple test and everything is working: https://dotnetfiddle.net/yUfgJW

```csharp
var document = new HtmlDocument();
document.LoadHtml("<a target=\"_blank\" href=\"$CFG->wwwroot/course/view.php?id=$course->id\">$shortname</a>");

var href = document.DocumentNode.SelectSingleNode("//a").GetAttributeValue("href", "");

Console.WriteLine(href);
```

(I also tried when reading a file)

So I'm probably missing something from my simple test. Knowing how to get the same issue as you will surely help me.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment] 2024-10-03 12:40
Hello @mikehenry1979-bah, 

Since our last conversation, we haven't heard from you. 

As previously mentioned we would need a runnable project to assist you. 

Let me know if you have questions. 

Best regards, 

Jon

**Comment by mikehenry1979-bah** [comment] 2024-10-03 16:31
Apologies, I’ve been pulled from that work for the immediate time. If you were able to get it to work, this issue can be closed.

From: Jonathan Magnan ***@***.***>
Sent: Thursday, October 3, 2024 8:41 AM
To: zzzprojects/html-agility-pack ***@***.***>
Cc: mikehenry1979-bah ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [zzzprojects/html-agility-pack] ">" inside "a" element "href" attribute causes value truncation (Issue #570)

Hello @mikehenry1979-bah, Since our last conversation, we haven't heard from you. As previously mentioned we would need a runnable project to assist you. Let me know if you have questions. Best regards, Jon — Reply to this email directly,


Hello @mikehenry1979-bah<https://urldefense.com/v3/__https:/github.com/mikehenry1979-bah__;!!May37g!NUMdpQtsDU8v4umVHtsSelbwoOeDsaZbl1U_YCJdu3nGQlc5l0b6JPB4qw_AnTLFaRFwMQ-fiiqr_Tnu574PdGOK$>,

Since our last conversation, we haven't heard from you.

As previously mentioned we would need a runnable project to assist you.

Let me know if you have questions.

Best regards,

Jon

**Comment by JonathanMagnan** [comment] 2024-10-04 12:45
Hello @mikehenry1979-bah 

Perfect, we will close it.

We will re-open it when you will be able to provide an example.

Best Regards,

Jon

**Closed by JonathanMagnan** 2024-10-04 12:45 UTC
