### ISSUE TITLE
Parent node being set wrong when swapping child nodes

### ISSUE THREAD

**Issue by alexalok** [zzzprojects/html-agility-pack#218] opened 2018-07-10 21:32 UTC
Hello, I'd like to report a possible bug in a library.

Suppose we have two child nodes that we want to swap.
```C#
var remNode = characterNode.SelectSingleNode("./item[@name='shg09_shop']");
var mc255Node = characterNode.SelectSingleNode("./item[@name='shg10_shop']");
Debug.Assert(remNode.ParentNode != null); //true
Debug.Assert(mc255Node.ParentNode != null); //true
```

For that we need to know their indeces
```C#
int remNodeIndex = characterNode.ChildNodes.IndexOf(remNode);
int mc255NodeIndex = characterNode.ChildNodes.IndexOf(mc255Node);
```

There we do the first swapping step. As expected, `remNode` becomes orphaned.
```C#
characterNode.ChildNodes.Replace(remNodeIndex, mc255Node);
Debug.Assert(remNode.ParentNode != null); //false
Debug.Assert(mc255Node.ParentNode != null); //true
```

There we finish the swapping. As a result, both `remNode` and `mc255Node` are part of `characterNode.ChildNodes` collection. However, `mc255Node.ParentNode` property returns `null`.
```C#
characterNode.ChildNodes.Replace(mc255NodeIndex, remNode);
Debug.Assert(remNode.ParentNode != null); //true
Debug.Assert(mc255Node.ParentNode != null); //false
```

From my understanding, this is not an expected behavior, but feel free to correct me if I'm wrong.

**Comment by JonathanMagnan** [comment] 2018-07-10 23:17
Hello @alexalok ,

> As a result, both remNode and mc255Node are part of characterNode.ChildNodes

It should not, or I'm missing something. Why `mc255NodeIndex` should be part of the collection if you replaced it? I made a test and everything work as expected I believe.

```csharp
string input = "<div><div>a</div></div><div><div>b</div></div>";
var htmlDoc = new HtmlAgilityPack.HtmlDocument();
htmlDoc.LoadHtml(input);

var root = htmlDoc.DocumentNode.SelectSingleNode("//div[1]");
var node1 = htmlDoc.DocumentNode.SelectSingleNode("//div[1]/div[1]");
var node2 = htmlDoc.DocumentNode.SelectSingleNode("//div[2]/div[1]");

root.ChildNodes.Replace(0, node2);
```

The node1 parent should be null and node2 parent be the root.

Do you think you could provide a "working" project example/test with this issue?

It will make easier/faster for my developer to getting started for investigating it.

_You can send it to info@zzzprojects.com if you need to keep the source private_

_We now always ask for a project since we found out that most issues are missing some essential information, have some syntax mistake or are resolved by the requestor when creating it_

_(Even if the issue seem very easy to reproduce, by getting a test project, it allow us to give a faster support and better experience for the support of all our free libraries)_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by alexalok** [comment] 2018-07-10 23:31
Hey, @JonathanMagnan 

I actually made 2 replacements. If we're talking in terms of the example you provided, the replacements are

```C#
root.ChildNodes.Replace(0, node2);
root.ChildNodes.Replace(1, node1);
```

so `node1` is still in the parent's childnodes collection.

**Comment by JonathanMagnan** [comment] 2018-07-10 23:36
My bad, now I understand ;)

Currently looking at it.

**Comment by JonathanMagnan** [comment] 2018-07-11 00:08
Hello @alexalok ,

It's possible to get the `html` used. I tried a few scenarios and so far they are all working.

Unfortunately, time is missing, so I would love to fix it but our time to reproduce it is limited.

**Comment by alexalok** [comment] 2018-07-11 00:11
Sure, I'll send it tomorrow to the email you provided. Thanks for the support!

**Comment by alexalok** [comment] 2018-07-12 12:12
Thanks for a detailed answer, @JonathanMagnan.
I ended up removing both nodes from a parent and then inserting them, but I believe cloning would work perfectly fine in my case as well.
Regarding the question whether an error should be thrown, I believe my example could be considered as an undefined behavior, so if existing application is upgraded throwing an error could be a way to signal its author that he probably has a flaw in logic. Something like `InvalidOperationException` with a message `The node does already exist in this ChildNode collection. Please, try cloning it first`.

**Closed** 2018-07-22 23:49 UTC
