### ISSUE TITLE
.NetStandart Load with proxy problem

### ISSUE THREAD

**Issue by cacheoff** [zzzprojects/html-agility-pack#59] opened 2017-08-01 21:29 UTC
In a Task.Run statement when we use HtmlWeb.Load() with IWebProxy and ICredentials parameters Task.Run statement never hits.

**Comment by JonathanMagnan** [comment] 2017-08-02 12:10
Hello @cacheoff ,

Thank you for reporting,

We will look at this issue very soon.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-08-02 19:57
Hello @cacheoff ,

A new version has been released v1.5.2-beta4,

We removed some code that was calling await for nothing and make sure to add `ConfigureAwait(false)` everywhere.

Let me know if we fixed `deadlock` caused by the library.

Best Regards,

Jonathan

**Comment by cacheoff** [comment] 2017-08-03 09:07
Hello Jonathan,

After hours of testing, i have noticed that the bug is not about your code.
"Task.Run" statement never hits even when it includes only a line such as
"var m = new HttpMethod("GET")". Therefore this is not a deadlock. I think
this is a bug of System.Net.Http library in .NETStandart framework.

2017-08-02 22:57 GMT+03:00 Jonathan Magnan <notifications@github.com>:

**Comment by JonathanMagnan** [comment] 2017-08-03 13:14
Which version of .NET Standard are you using?

I don't remember the link, but I have heard of such issue in .NET Standard 1.3

Best Regards,

Jonathan

**Comment by cacheoff** [comment] 2017-08-03 14:10
I was using .NetStandard 1.5. But because of that issue I converted my project to .NetFramework 4.6. Now i have no problem anymore. Everything works properly.

**Comment by JonathanMagnan** [comment] 2017-08-03 23:32
Yup, that's why I released a version for .NET Standard 1.6

When I have asked to MysticMind (https://github.com/mysticmind/mysticmind-htmlagilitypack) which is the one that made almost all the code to support .NET Standard, he answering me this:

> When I tried with NetStandard 1.3, it resulted in several errors pertaining to System.Net.Http and others. Then I read some material online and found out that NetStandard 1.6 has better support covering more surface area of libraries, it which readily worked with few tweaks/changes.

I still released a version for 1.3 since some people wanted to only use it without loading the HTML directly from the web.

I will close this issue then since you moved back to .NET Framework 4.6 and anyway, I don't think there is something I can really do.

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2017-08-03 23:32 UTC
