### ISSUE TITLE
Attribute values are not HTML decoded

### ISSUE THREAD

**Issue by zgabi** [zzzprojects/html-agility-pack#125] opened 2017-12-20 07:52 UTC
When I get the attribute value of a node the result is not HTML decoded. When I read it with XmlDocument it is decoded. I think it should be decoded in HAP, too.

```
            var doc = new HtmlDocument();
            doc.Load(fileName);
            var link = doc.GetElementbyId("link1");
            var href = link.GetAttributeValue("href", null);
            Console.WriteLine("html:" + href);

            var xml = new XmlDocument();
            xml.Load(fileName);
            var link2 = xml.DocumentElement.SelectSingleNode("//html/body/a");
            var href2 = link2.Attributes["href"].InnerText;
            Console.WriteLine("xml:" + href2);

```

Result:
html:http://example.com/?q=1&amp;r=2
xml:http://example.com/?q=1&r=2

The test file:
```
<html>
<body>
<a id="link1" href="http://example.com/?q=1&amp;r=2">Test</a>
</body>
</html>
```

**Comment by JonathanMagnan** [comment] 2017-12-20 11:39
Hello @romainecarter ,

Thank you for reporting, we will look at it.

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment] 2017-12-22 17:01
Hello @zgabi ,

You are correct about what is the right value our library should return. But due to the number of people using this library and the impact of breaking this code, we cannot do this fix by default.

Some people already reported us in the past some issue when we fixed the value in the correct way.

What I could propose is adding this fix only when the option `BackwardCompatibility = false`.

So people already using our library are not impacted and people with this options have some of the latest fixes.

Best Regards,

Jonathan

**Comment by zgabi** [comment] 2017-12-22 17:18
Hello @JonathanMagnan 

That is ok for me.

Is it possible to add a static default setting for this compatibility flag, like this?

In HtmlDocument.cs:
```
        public static bool DefaultBackwardCompatibility = true;

        /// <summary>True to stay backward compatible with previous version of HAP. This option does not guarantee 100% compatibility.</summary>
        public bool BackwardCompatibility = DefaultBackwardCompatibility;

```
So all the new HTML documents will be correct if you set the `DefaultBackwardCompatibility `to `false`.

The name and the position of the property is only a suggestion, you can put it anywhere. I don't know, maybe HAP has a static configuration place. 

Thanks,
Gábor

**Comment by JonathanMagnan** [comment] 2017-12-22 22:21
Hello @jnyrup  ,

The v1.6.10 has been released.

I have added a builder as I normally do in my other projects to perform some global config. You can now use the `DefaultBuilder` options to specify all configurations that will be applied to newly HtmlDocument

```csharp
HtmlAgilityPack.HtmlDocument.DefaultBuilder = builder => builder.BackwardCompatibility = false;
```

Let me know if there is something else we can do.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment] 2018-01-09 21:31
Hello @jnyrup ,

I will close this issue since it should be solved.

Feel free to reopen it if there is something else.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by zgabi** [comment] 2019-03-18 08:54
Hi,

Now you have added a breaking change for the P tags. Why don't you set this BackwardCompatibility setting also to false, too? 
When somebody needs the old mode, then he can set it to true. Your library would be more compatible with the modern web browsers.

**Comment by GeorgDangl** [comment] 2019-03-18 09:55
+1 for me. I'm using the library to transform Html to plain text, and the latest changes in 1.10.0 made lots of tests red. I'd be happy with setting the default to `false`, to continue with the old behavior if nothing is explicitly set.

**Comment by JonathanMagnan** [comment] 2019-03-18 10:17
The library needs a big revamp to make it `HTML5` compatible. We already know exactly how to do it but unfortunately, time is always missing for a free library ;(

It's possible to report in which case the `P` tag currently doesn't longer work? We will review it on our side today by setting tag omission and other stuff: http://w3c.github.io/html-reference/p.html

It's possible that we revert our change, but I would like to try it at least as the old setting will never work. Too much issue has been reported with the `P` tag caused by this line: https://github.com/zzzprojects/html-agility-pack/blob/master/src/HtmlAgilityPack.Shared/HtmlNode.cs#L133

**Comment by JonathanMagnan** [comment] 2019-03-18 10:34
A new version `1.10.1` is now released.

All "implicit ending" should now be handled correctly.

A new version will be available later today as we have found a major issue last week about how a tag is not ended correctly. It will certainly fix a lot of additional issues.

As said, I believe it worth the try to change the behavior if we can make it quickly work correctly.

@GeorgDangl , if you could provide us your test project to info@zzzprojects.com, it will greatly make this process faster.

**Comment by GeorgDangl** [comment] 2019-03-18 10:39
I'll look at the test and extract the changed behavior that affected me.

I think it was when `<p>` elements had nested children, something like this:
`<p>Begin<div>Inner</div>End</p>`. The parsing related to that has changed.

I'll report back when I've got something more detailed.

**Comment by GeorgDangl** [comment] 2019-03-18 11:24
You can reproduce it with this test case:

```csharp
[Fact]
public void ChangesToPHandling()
{
    var input = "<p>Begin<div>Inner</div>End</p>";
    var doc = new HtmlAgilityPack.HtmlDocument();
    doc.LoadHtml(input);
    var docNode = doc.DocumentNode;

    // Check tree is correct
    Assert.Single(docNode.ChildNodes);
    Assert.Equal("p", docNode.ChildNodes[0].Name);

    var pRootNode = docNode.ChildNodes[0];
    Assert.Equal(3, pRootNode.ChildNodes.Count);
    Assert.Equal("Begin", pRootNode.ChildNodes[0].InnerText);
    Assert.Equal("Inner", pRootNode.ChildNodes[1].InnerText);
    Assert.Equal("End", pRootNode.ChildNodes[2].InnerText);
}
```

This succeeds in `1.9.1` but fails in `1.10.1`.

Here's how the trees are generated:

v1.10.1:
Tree:

- p: `Begin`
- div: `Inner`
- #text: `End`

v1.9.1:
Tree:

- p
  - #text: `Begin`
  - div: `Inner`
  - #text: `End`

**Comment by GeorgDangl** [comment] 2019-03-18 11:47
Additionally, this parses correctly when replacing the inner `div` with a `span` element.

`div` is actually not a valid child element of `p`, so I guess the behaviour is correct within the Html specification. But it would be great to be able to still parse such trees, since not every string I encounter conforms to the Html spec:)

**Comment by JonathanMagnan** [comment] 2019-03-18 12:20
The v1.10.1 is what we are expecting. A `div` cannot be inside `p` as you specified.

You can turn on globally the default P behavior using:
```csharp
HtmlDocument.DisableBehavaiorTagP = true;
```

We are currently looking all prerequistes if we want to create a `HAP V2.0`. I have added an option to disable all those kind of fixes.

**Comment by GeorgDangl** [comment] 2019-03-18 12:27
The test case above fails with both settings for `HtmlDocument.DisableBehavaiorTagP`, neither `true` nor `false` make any difference.

Is there another option to restore the original behavior from `v1.9.1`? Optionally, can you point me to the commit where this change was introduced? I'd be very happy to create a pull request and make this a configurable option for the document.

Unfortunately, I have to parse documents that may contain `<div>` inside of `<p>`. So far, I've always been quite happy with HtmlAgilityPack parsing the DOM exactly as given, but I understand that you want to make some corrections during parsing.

**Comment by JonathanMagnan** [comment] 2019-03-18 12:33
You are right,

I forget that we added implicit end logic here: https://github.com/zzzprojects/html-agility-pack/blob/master/src/HtmlAgilityPack.Shared/HtmlDocument.cs#L1797

I would make the change and release it in a few minutes.

**Comment by JonathanMagnan** [comment] 2019-03-18 12:45
The v1.10.2 is now released.

We added your unit test to make sure we always support this case.

Let me know if everything is correct on your side with `HtmlDocument.DisableBehavaiorTagP = false`

**Comment by GeorgDangl** [comment] 2019-03-18 15:53
So far, everything looks good on my side, except one issue:

The static constructor for `HtmlNode` has the following check:

```csharp
if (!HtmlDocument.DisableBehavaiorTagP)
{
    ElementsFlags.Add("p", HtmlElementFlag.Empty | HtmlElementFlag.Closed);
}
```

So there can be situations where the static constructor for `HtmlNode` is invoked, then the `HtmlDocument.DisableBehavaiorTagP` property is set. This led to flaky tests on my side, since I'm using xUnit and this randomized the order of execution - in some test runs, `HtmlNode` was initialized before, and in some, after the field was set in `HtmlDocument`.

There's no update or synchronization mechanism between these two.

I've updated my classes to perform this action:

```chsarp
private static void EnsureHtmlAgilityPackLegacyBehavior()
{
    if (!HtmlDocument.DisableBehavaiorTagP)
    {
        HtmlDocument.DisableBehavaiorTagP = false;
    }
    if (!HtmlNode.ElementsFlags.ContainsKey("p"))
    {
        HtmlNode.ElementsFlags.Add("p", HtmlElementFlag.Empty | HtmlElementFlag.Closed);
    }
}
```

To solve this directly in **HtmlAgilityPack**, maybe you could implement something like this:

```csharp
/// <summary>True to disable, false to enable the behavaior tag p.</summary>
internal static bool DisableBehavaiorTagP = true;
/// <summary>True to disable, false to enable the behavaior tag p.</summary>
public static void SetLegacyBehaviorForTagP(bool useLegacy)
{
    DisableBehavaiorTagP = useLegacy;
    if (useLegacy && !HtmlNode.ElementsFlags.ContainsKey("p"))
    {
        HtmlNode.ElementsFlags.Add("p", HtmlElementFlag.Empty | HtmlElementFlag.Closed);
    }
    else if (!useLegacy && HtmlNode.ElementsFlags.ContainsKey("p"))
    {
        HtmlNode.ElementsFlags.Remove("p");
    }
}
public static bool UseLegacyBehaviourForTagP()
{
    return DisableBehavaiorTagP;
}
```
and just remove the logic in the static constructor for `HtmlNode` completely.

Btw, thank you very much for the quick replies and the fast releases, I really appreciate that:)

**Comment by JonathanMagnan** [comment] 2019-03-19 01:36
Hello @GeorgDangl ,

Sure, we will look at it and release something similar or exactly this tomorrow.

No problem ;)

**Comment by JonathanMagnan** [comment] 2019-03-19 20:43
Hello @GeorgDangl ,

The v1.11.0 has been released.

We fixed the spelling mistake in `DisableBehavaiorTagP` to `DisableBehaviorTagP `. We have kept it as a property since we know some people already use it but we added your code inside the `set` to make it work exactly as you specified.

This version also contains another major change for when ending tag is missing, so make sure to test it.

Let me know if everything is working as expected.

**Comment by GeorgDangl** [comment] 2019-03-19 21:36
Thank you!
So far, I've noticed no regressions with v1.11.0, but I will have to run the tests also in dependent projects. I'll update here.

**Closed** 2019-03-31 10:20 UTC

**Comment by GeorgDangl** [comment] 2019-03-31 10:24
Just wanted to report back, I've upgraded to the latest version, no regressions in any downstream projects for me. Thank you very much!

**Comment by JonathanMagnan** [comment] 2019-03-31 23:05
Great @GeorgDangl ,

Thank for letting us know :)
