### ISSUE TITLE
calling RemoveAt on an instance of HtmlNodeCollection throwing exception

### ISSUE THREAD

**Issue by goforgold** [zzzprojects/html-agility-pack#26] opened 2017-06-27 06:11 UTC
I've a valid instance of `HtmlNodeCollection` having 78 member (retrieved using `.Count`) as below:

`var regionRows = ...`

I need to remove very first element from the `regionRows`.

I tried calling `regionRows.RemoveAt(0)`, but it is throwing an exception `System.NullReferenceException: Object reference not set to an instance of an object`.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at HtmlAgilityPack.HtmlNodeCollection.RemoveAt(Int32 index) in ..... 250
```

Any suggestion? I want to do it without LINQ.

**Comment by JonathanMagnan** [comment] 2017-06-27 11:14
Thank you for reporting.

My developer will look at this issue this week.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-07-08 12:01
Hello @goforgold ,

Could you provide an example that's not working?

My developer is not able to reproduce this issue.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-08-07 14:16
Hello @goforgold ,

Since no example has been provided, we will close this issue.

Feel free to re-open it if you can add an example,

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2017-08-07 14:16 UTC
