### ISSUE TITLE
HtmlNode.HasClass not recognizing classes starting with a whitespace

### ISSUE THREAD

**Issue by Skubidus** [zzzprojects/html-agility-pack#312] opened 2019-07-06 17:35 UTC
### Description
The title pretty much says it all. I am having trouble getting HasClass to recognize classes which begin with a whitespace (class=" disabled"). Same goes for GetClasses(). I don't get an exception or anything - the HtmlNode is just considered to not have any classes even though it clearly does have one.

### Further technical details
- HAP version: 1.11.8
- NET version (net472, netcore, etc.): .Net 4.7.2

**Comment by JonathanMagnan** [comment] 2019-07-08 04:13
Hello @Jon,

Do you think you could provide a project sample with this issue?

Or create a Fiddle that reproduce the issue: https://dotnetfiddle.net/25Vjsn

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by Skubidus** [comment] 2019-07-08 04:36
Will do when I get back from work

**Comment by Skubidus** [comment] 2019-07-11 13:35
Hi,

sorry, I've been busy the last couple days.

I just looked at my project again and can't just easily extract the important part where the error itself occurs. Also I don't want to send you the entire project.

But the problem itself is fairly simple:

I ready stuff from a website which has a table somewhere in the html code and within that table the tr-elements either look like

`<tr class>`
or
`<tr class=" disabled">`

If the element has the class "disabled" then neither the HasClass()-method nor the GetClasses()-method won't recognize it.

**Comment by EvgeniyZ** [comment] 2019-09-02 15:28
@Skubidus hi there, please, take a look at PR https://github.com/zzzprojects/html-agility-pack/pull/322
I've written unit tests that are passed and they're cover your scenario. Can you provide more details regarding this issue or close it, thank you.

**Comment by Skubidus** [comment] 2019-09-03 07:02
Thanks for the reply.
I took just a quick glance at your unit testing method and it appears that your input variable to test everything with is set up wrong.

Your's says:

`var input = @"<a class="" disabled""></a>";`

while mine (which failed for me) says (note the whitespace in front of the class name " disabled" which is not the html keyword disabled):

`<tr class=" disabled">`

**Comment by EvgeniyZ** [comment] 2019-09-03 09:05
@Skubidus double quotes is a escape character for ", so it's a test method for 
`<a class=" disabled"></a>`

**Comment by Skubidus** [comment] 2019-09-03 16:57
ok after debugging and testing some more I found out that the problem is not that the HasClass-method doesn't recognize the html-elements with the " disabled"-class but it seems like that in fact the .NET HttpClient.GetStringAsync()-method doesn't recognize the class and just returns

`<tr class="">`

Well, that explains alot.

**Comment by JonathanMagnan** [comment] 2019-09-04 20:37
So I guess we can close it?

Let me know if we should re-open it.

**Closed by JonathanMagnan** 2019-09-04 20:37 UTC
