### ISSUE TITLE
Timed out exception after several minutes!

### ISSUE THREAD

**Issue by mtissington** [zzzprojects/html-agility-pack#101] opened 2017-11-09 12:22 UTC
Why does the following fail? What is strange about 'www.cars.com' ?
Often the exception object is null too - looks like a com error?

```csharp
using System;
using System.Xml;
using HtmlAgilityPack;
					
public class Program
{
	public static void Main()
	{
		var html = @"http://www.cars.com/";

        HtmlWeb web = new HtmlWeb();

        var htmlDoc = web.Load(html);

        var node = htmlDoc.DocumentNode.SelectSingleNode("//head/title");

        Console.WriteLine("Node Name: " + node.Name + "\n" + node.OuterHtml);		
	}
}
```

**Comment by JonathanMagnan** [comment] 2017-11-09 14:27
Hello @mtissington ,

Thank you for reporting. I'm not quite sure why this is happening but I will investigate this case this weekend.

Meanwhile you can use either

## LoadFromBrowser
```csharp
var url = @"http://www.cars.com/";

HtmlWeb web = new HtmlWeb();

var htmlDoc = web.LoadFromBrowser(url);

var node = htmlDoc.DocumentNode.SelectSingleNode("//head/title");
```

## LoadHtml (Custom)
```csharp
public void Main()
{
	var url = @"http://www.cars.com/";

	var htmlDoc = new HtmlAgilityPack.HtmlDocument();
	htmlDoc.LoadHtml(GetResponse(url));

	var node = htmlDoc.DocumentNode.SelectSingleNode("//head/title");
}
public static string GetResponse(string url)
{
    System.Net.HttpWebRequest req = (System.Net.HttpWebRequest)System.Net.HttpWebRequest.Create("http://www.cars.com/");

    string source = String.Empty;
    try
    {
        using (System.Net.WebResponse webResponse = req.GetResponse())
        {
            using (HttpWebResponse httpWebResponse = webResponse as HttpWebResponse)
            {
                StreamReader reader;
                if (httpWebResponse.ContentEncoding.ToLower().Contains("gzip"))
                {
                    reader = new StreamReader(new GZipStream(httpWebResponse.GetResponseStream(), CompressionMode.Decompress));
                }
                else if (httpWebResponse.ContentEncoding.ToLower().Contains("deflate"))
                {
                    reader = new StreamReader(new DeflateStream(httpWebResponse.GetResponseStream(), CompressionMode.Decompress));
                }
                else
                {
                    reader = new StreamReader(httpWebResponse.GetResponseStream());
                }
                source = reader.ReadToEnd();
            }
        }

        req.Abort();

        return source;
    }
    catch (Exception ex)
    {
        throw;
    }
}
```

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-11-11 14:41
Hello @mtissington ,

It seems the problem is only the default `UserAgent` used in the `WebRequest`.

**Comment by JonathanMagnan** [comment] 2017-11-11 14:47
Hello @mtissington ,

I don't think any fix will be done for now for this request.

I believe the `host` block this request because he found out this request seems to come from a `bot` because of the default `UserAgent`: 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:x.x.x) Gecko/20041107 Firefox/x.x`

You can fix it by setting the `UserAgent` to an empty string

```csharp
var html = @"http://www.cars.com/";
HtmlWeb web = new HtmlWeb() { UserAgent = "" };
var htmlDoc = web.Load(html);
var node = htmlDoc.DocumentNode.SelectSingleNode("//head/title");
```

Let me know if that successfully fix your issue.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-11-21 01:47
Hello @mtissington ,

Did you successfully make it work?

As said, I do not believe any fix will be provided so I will close this issue but feel free to reopen it if you have some question.

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_

**Closed** 2017-11-21 01:47 UTC
